# Generated by Django 3.1.6 on 2021-02-07 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psycho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='psycho_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='psycho.psychomaster'),
        ),
    ]
