# Generated by Django 3.1.6 on 2021-02-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho', '0002_auto_20210207_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychomaster',
            name='own_id',
            field=models.CharField(default='default_own_id', max_length=255),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='own_id',
            field=models.CharField(default='default_own_id', max_length=255),
        ),
    ]
